import {
  ArrowLeftRight,
  Baby,
  Backpack,
  Banknote,
  Beer,
  Bike,
  Bone,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Car,
  CarFront,
  CarTaxiFront,
  ChartLine,
  CircleParking,
  ClipboardCheck,
  Coffee,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  FileCheck,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandHeart,
  HeartPulse,
  Home,
  House,
  Key,
  Landmark,
  Laptop,
  Luggage,
  Music,
  Package,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  Repeat,
  School,
  Scissors,
  Shield,
  ShieldCheck,
  ShieldHalf,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  SprayCan,
  SquareParking,
  Stethoscope,
  Store,
  Syringe,
  Target,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Undo2,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import { t } from '@/shared/lib/i18n';
import { cn } from '@/shared/lib/utils';

/**
 * The icons a category is marked with.
 *
 * ── Why a table and not `lucide[name]` ──────────────────────────────────────
 * Because resolving the name against the whole package forces importing it
 * whole: fifteen hundred icons in the bundle to show fifty. With an
 * explicit table, the bundler takes only these.
 *
 * ── Why the name is stored in lowercase and with hyphens ────────────────────
 * Because that is how the ones seeded by the initial dictionary are already stored
 * —`house`, `spray-can`, `graduation-cap`— and it is also the name under which
 * lucide publishes them. Storing `House` would have left two formats in the same
 * column and an icon that shows or not depending on who created it.
 *
 * ── Why the table is longer than the list that is offered ───────────────────
 * FIFTY are OFFERED, the ones that make sense for a spending category. But the
 * initial dictionary seeds sixty-six different names, and many are not
 * among those fifty: if the table only had the eligible ones, all
 * those categories would lose their icon the day someone opened this
 * screen. The table covers the union; the picker, only the eligible ones.
 */
const BY_NAME: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  baby: Baby,
  backpack: Backpack,
  banknote: Banknote,
  beer: Beer,
  bike: Bike,
  bone: Bone,
  book: Book,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  car: Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  'chart-line': ChartLine,
  'circle-parking': CircleParking,
  'clipboard-check': ClipboardCheck,
  coffee: Coffee,
  'credit-card': CreditCard,
  dog: Dog,
  droplet: Droplet,
  dumbbell: Dumbbell,
  'file-check': FileCheck,
  'file-text': FileText,
  film: Film,
  flame: Flame,
  fuel: Fuel,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  home: Home,
  house: House,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  luggage: Luggage,
  music: Music,
  package: Package,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  percent: Percent,
  'piggy-bank': PiggyBank,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  school: School,
  scissors: Scissors,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sofa: Sofa,
  'spray-can': SprayCan,
  'square-parking': SquareParking,
  stethoscope: Stethoscope,
  store: Store,
  syringe: Syringe,
  target: Target,
  ticket: Ticket,
  'train-front': TrainFront,
  'trending-up': TrendingUp,
  tv: Tv,
  'undo-2': Undo2,
  'user-round': UserRound,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

/** What is offered when creating or editing a category. */
export const CATEGORY_ICONS: readonly { name: string; label: string }[] = [
  { name: 'house', label: t('ui.icons.home') },
  { name: 'zap', label: t('ui.icons.energy') },
  { name: 'droplet', label: t('ui.icons.water') },
  { name: 'flame', label: t('ui.icons.gas') },
  { name: 'wifi', label: t('ui.icons.internet') },
  { name: 'smartphone', label: t('ui.icons.phone') },
  { name: 'tv', label: t('ui.icons.tv') },
  { name: 'spray-can', label: t('ui.icons.cleaning') },
  { name: 'shopping-cart', label: t('ui.icons.groceries') },
  { name: 'utensils-crossed', label: t('ui.icons.restaurants') },
  { name: 'coffee', label: t('ui.icons.coffee') },
  { name: 'beer', label: t('ui.icons.outings') },
  { name: 'car', label: t('ui.icons.vehicle') },
  { name: 'fuel', label: t('ui.icons.fuel') },
  { name: 'bus', label: t('ui.icons.transport') },
  { name: 'bike', label: t('ui.icons.bicycle') },
  { name: 'plane', label: t('ui.icons.travel') },
  { name: 'circle-parking', label: t('ui.icons.parking') },
  { name: 'heart-pulse', label: t('ui.icons.health') },
  { name: 'stethoscope', label: t('ui.icons.appointments') },
  { name: 'pill', label: t('ui.icons.medicine') },
  { name: 'dumbbell', label: t('ui.icons.gym') },
  { name: 'graduation-cap', label: t('ui.icons.education') },
  { name: 'book-open', label: t('ui.icons.books') },
  { name: 'backpack', label: t('ui.icons.school') },
  { name: 'baby', label: t('ui.icons.baby') },
  { name: 'dog', label: t('ui.icons.pets') },
  { name: 'shirt', label: t('ui.icons.clothes') },
  { name: 'scissors', label: t('ui.icons.hairdresser') },
  { name: 'gift', label: t('ui.icons.gifts') },
  { name: 'party-popper', label: t('ui.icons.celebrations') },
  { name: 'film', label: t('ui.icons.cinema') },
  { name: 'music', label: t('ui.icons.music') },
  { name: 'gamepad-2', label: t('ui.icons.videogames') },
  { name: 'ticket', label: t('ui.icons.tickets') },
  { name: 'laptop', label: t('ui.icons.technology') },
  { name: 'briefcase', label: t('ui.icons.work') },
  { name: 'landmark', label: t('ui.icons.taxes') },
  { name: 'credit-card', label: t('ui.icons.cards') },
  { name: 'banknote', label: t('ui.icons.cash') },
  { name: 'piggy-bank', label: t('ui.icons.savings') },
  { name: 'receipt', label: t('ui.icons.bills') },
  { name: 'shield-check', label: t('ui.icons.insurance') },
  { name: 'wrench', label: t('ui.icons.maintenance') },
  { name: 'sofa', label: t('ui.icons.household') },
  { name: 'hand-heart', label: t('ui.icons.donations') },
  { name: 'store', label: t('ui.icons.shopping') },
  { name: 'package', label: t('ui.icons.shipping') },
  { name: 'users', label: t('ui.icons.family') },
  { name: 'wallet', label: t('ui.icons.general') },
];

/**
 * Paints the icon of a category.
 *
 * With a name that is not in the table —one seeded long ago, one written
 * by hand in the database— NOTHING is painted instead of a question mark: a
 * wrong icon says something false about the category, and none says nothing, which is
 * exactly what is known.
 */
export function CategoryIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = name ? BY_NAME[name] : undefined;
  if (!Icon) return null;

  return <Icon className={cn('size-4', className)} aria-hidden="true" />;
}
