import {
  ArrowLeftRight,
  Baby,
  Backpack,
  Banknote,
  Beer,
  Bike,
  Bone,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Car,
  CarFront,
  CarTaxiFront,
  ChartLine,
  CircleParking,
  ClipboardCheck,
  Coffee,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  FileCheck,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandHeart,
  HeartPulse,
  Home,
  House,
  Key,
  Landmark,
  Laptop,
  Luggage,
  Music,
  Package,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  Repeat,
  School,
  Scissors,
  Shield,
  ShieldCheck,
  ShieldHalf,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  SprayCan,
  SquareParking,
  Stethoscope,
  Store,
  Syringe,
  Target,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Undo2,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import { t } from '@/shared/lib/i18n';
import { cn } from '@/shared/lib/utils';

/**
 * Los iconos con los que se marca una categoría.
 *
 * ── Por qué una tabla y no `lucide[nombre]` ─────────────────────────────────
 * Porque resolver el nombre contra el paquete entero obliga a importarlo
 * entero: mil quinientos iconos en el bundle para enseñar cincuenta. Con una
 * tabla explícita, el empaquetador se lleva solo estos.
 *
 * ── Por qué el nombre se guarda en minúsculas y con guiones ─────────────────
 * Porque es como ya están guardados los que sembró el diccionario inicial
 * —`house`, `spray-can`, `graduation-cap`— y es además el nombre con el que
 * lucide los publica. Guardar `House` habría dejado dos formatos en la misma
 * columna y un icono que se ve o no según quién lo creó.
 *
 * ── Por qué la tabla es más larga que la lista que se ofrece ────────────────
 * Se OFRECEN cincuenta, los que tienen sentido para una categoría de gasto. Pero el
 * diccionario inicial siembra sesenta y seis nombres distintos, y muchos no
 * están entre esos cincuenta: si la tabla solo tuviera los elegibles, todos
 * esas categorías se quedarían sin su icono el día que alguien abriera esta
 * pantalla. La tabla cubre la unión; el selector, solo lo elegible.
 */
const POR_NOMBRE: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  baby: Baby,
  backpack: Backpack,
  banknote: Banknote,
  beer: Beer,
  bike: Bike,
  bone: Bone,
  book: Book,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  car: Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  'chart-line': ChartLine,
  'circle-parking': CircleParking,
  'clipboard-check': ClipboardCheck,
  coffee: Coffee,
  'credit-card': CreditCard,
  dog: Dog,
  droplet: Droplet,
  dumbbell: Dumbbell,
  'file-check': FileCheck,
  'file-text': FileText,
  film: Film,
  flame: Flame,
  fuel: Fuel,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  home: Home,
  house: House,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  luggage: Luggage,
  music: Music,
  package: Package,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  percent: Percent,
  'piggy-bank': PiggyBank,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  school: School,
  scissors: Scissors,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sofa: Sofa,
  'spray-can': SprayCan,
  'square-parking': SquareParking,
  stethoscope: Stethoscope,
  store: Store,
  syringe: Syringe,
  target: Target,
  ticket: Ticket,
  'train-front': TrainFront,
  'trending-up': TrendingUp,
  tv: Tv,
  'undo-2': Undo2,
  'user-round': UserRound,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

/** Lo que se ofrece al crear o editar una categoría. */
export const ICONOS_DE_CATEGORIA: readonly { nombre: string; etiqueta: string }[] = [
  { nombre: 'house', etiqueta: t('ui.icons.home') },
  { nombre: 'zap', etiqueta: t('ui.icons.energy') },
  { nombre: 'droplet', etiqueta: t('ui.icons.water') },
  { nombre: 'flame', etiqueta: t('ui.icons.gas') },
  { nombre: 'wifi', etiqueta: t('ui.icons.internet') },
  { nombre: 'smartphone', etiqueta: t('ui.icons.phone') },
  { nombre: 'tv', etiqueta: t('ui.icons.tv') },
  { nombre: 'spray-can', etiqueta: t('ui.icons.cleaning') },
  { nombre: 'shopping-cart', etiqueta: t('ui.icons.groceries') },
  { nombre: 'utensils-crossed', etiqueta: t('ui.icons.restaurants') },
  { nombre: 'coffee', etiqueta: t('ui.icons.coffee') },
  { nombre: 'beer', etiqueta: t('ui.icons.outings') },
  { nombre: 'car', etiqueta: t('ui.icons.vehicle') },
  { nombre: 'fuel', etiqueta: t('ui.icons.fuel') },
  { nombre: 'bus', etiqueta: t('ui.icons.transport') },
  { nombre: 'bike', etiqueta: t('ui.icons.bicycle') },
  { nombre: 'plane', etiqueta: t('ui.icons.travel') },
  { nombre: 'circle-parking', etiqueta: t('ui.icons.parking') },
  { nombre: 'heart-pulse', etiqueta: t('ui.icons.health') },
  { nombre: 'stethoscope', etiqueta: t('ui.icons.appointments') },
  { nombre: 'pill', etiqueta: t('ui.icons.medicine') },
  { nombre: 'dumbbell', etiqueta: t('ui.icons.gym') },
  { nombre: 'graduation-cap', etiqueta: t('ui.icons.education') },
  { nombre: 'book-open', etiqueta: t('ui.icons.books') },
  { nombre: 'backpack', etiqueta: t('ui.icons.school') },
  { nombre: 'baby', etiqueta: t('ui.icons.baby') },
  { nombre: 'dog', etiqueta: t('ui.icons.pets') },
  { nombre: 'shirt', etiqueta: t('ui.icons.clothes') },
  { nombre: 'scissors', etiqueta: t('ui.icons.hairdresser') },
  { nombre: 'gift', etiqueta: t('ui.icons.gifts') },
  { nombre: 'party-popper', etiqueta: t('ui.icons.celebrations') },
  { nombre: 'film', etiqueta: t('ui.icons.cinema') },
  { nombre: 'music', etiqueta: t('ui.icons.music') },
  { nombre: 'gamepad-2', etiqueta: t('ui.icons.videogames') },
  { nombre: 'ticket', etiqueta: t('ui.icons.tickets') },
  { nombre: 'laptop', etiqueta: t('ui.icons.technology') },
  { nombre: 'briefcase', etiqueta: t('ui.icons.work') },
  { nombre: 'landmark', etiqueta: t('ui.icons.taxes') },
  { nombre: 'credit-card', etiqueta: t('ui.icons.cards') },
  { nombre: 'banknote', etiqueta: t('ui.icons.cash') },
  { nombre: 'piggy-bank', etiqueta: t('ui.icons.savings') },
  { nombre: 'receipt', etiqueta: t('ui.icons.bills') },
  { nombre: 'shield-check', etiqueta: t('ui.icons.insurance') },
  { nombre: 'wrench', etiqueta: t('ui.icons.maintenance') },
  { nombre: 'sofa', etiqueta: t('ui.icons.household') },
  { nombre: 'hand-heart', etiqueta: t('ui.icons.donations') },
  { nombre: 'store', etiqueta: t('ui.icons.shopping') },
  { nombre: 'package', etiqueta: t('ui.icons.shipping') },
  { nombre: 'users', etiqueta: t('ui.icons.family') },
  { nombre: 'wallet', etiqueta: t('ui.icons.general') },
];

/**
 * Pinta el icono de una categoría.
 *
 * Con un nombre que no está en la tabla —uno sembrado hace tiempo, uno escrito
 * a mano en la base— no se pinta NADA en vez de pintar un interrogante: un
 * icono equivocado dice algo falso dla categoría, y ninguno no dice nada, que es
 * exactamente lo que se sabe.
 */
export function IconoDeCategoria({
  nombre,
  className,
}: {
  nombre?: string | null;
  className?: string;
}) {
  const Icono = nombre ? POR_NOMBRE[nombre] : undefined;
  if (!Icono) return null;

  return <Icono className={cn('size-4', className)} aria-hidden="true" />;
}
