import {
  ArrowLeftRight,
  Baby,
  Backpack,
  Banknote,
  Beer,
  Bike,
  Bone,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Car,
  CarFront,
  CarTaxiFront,
  ChartLine,
  CircleParking,
  ClipboardCheck,
  Coffee,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  FileCheck,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandHeart,
  HeartPulse,
  Home,
  House,
  Key,
  Landmark,
  Laptop,
  Luggage,
  Music,
  Package,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  Repeat,
  School,
  Scissors,
  Shield,
  ShieldCheck,
  ShieldHalf,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  SprayCan,
  SquareParking,
  Stethoscope,
  Store,
  Syringe,
  Target,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Undo2,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import { cn } from '@/lib/utils';

/**
 * Los iconos con los que se marca una categoría.
 *
 * ── Por qué una tabla y no `lucide[nombre]` ─────────────────────────────────
 * Porque resolver el nombre contra el paquete entero obliga a importarlo
 * entero: mil quinientos iconos en el bundle para enseñar cincuenta. Con una
 * tabla explícita, el empaquetador se lleva solo estos.
 *
 * ── Por qué el nombre se guarda en minúsculas y con guiones ─────────────────
 * Porque es como ya están guardados los que sembró el diccionario inicial
 * —`house`, `spray-can`, `graduation-cap`— y es además el nombre con el que
 * lucide los publica. Guardar `House` habría dejado dos formatos en la misma
 * columna y un icono que se ve o no según quién lo creó.
 *
 * ── Por qué la tabla es más larga que la lista que se ofrece ────────────────
 * Se OFRECEN cincuenta, los que tienen sentido para una categoría de gasto. Pero el
 * diccionario inicial siembra sesenta y seis nombres distintos, y muchos no
 * están entre esos cincuenta: si la tabla solo tuviera los elegibles, todos
 * esas categorías se quedarían sin su icono el día que alguien abriera esta
 * pantalla. La tabla cubre la unión; el selector, solo lo elegible.
 */
const POR_NOMBRE: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  'baby': Baby,
  'backpack': Backpack,
  'banknote': Banknote,
  'beer': Beer,
  'bike': Bike,
  'bone': Bone,
  'book': Book,
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'building': Building,
  'building-2': Building2,
  'bus': Bus,
  'car': Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  'chart-line': ChartLine,
  'circle-parking': CircleParking,
  'clipboard-check': ClipboardCheck,
  'coffee': Coffee,
  'credit-card': CreditCard,
  'dog': Dog,
  'droplet': Droplet,
  'dumbbell': Dumbbell,
  'file-check': FileCheck,
  'file-text': FileText,
  'film': Film,
  'flame': Flame,
  'fuel': Fuel,
  'gamepad-2': Gamepad2,
  'gift': Gift,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  'home': Home,
  'house': House,
  'key': Key,
  'landmark': Landmark,
  'laptop': Laptop,
  'luggage': Luggage,
  'music': Music,
  'package': Package,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'percent': Percent,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'plane': Plane,
  'plus': Plus,
  'receipt': Receipt,
  'repeat': Repeat,
  'school': School,
  'scissors': Scissors,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'smartphone': Smartphone,
  'smile': Smile,
  'sofa': Sofa,
  'spray-can': SprayCan,
  'square-parking': SquareParking,
  'stethoscope': Stethoscope,
  'store': Store,
  'syringe': Syringe,
  'target': Target,
  'ticket': Ticket,
  'train-front': TrainFront,
  'trending-up': TrendingUp,
  'tv': Tv,
  'undo-2': Undo2,
  'user-round': UserRound,
  'users': Users,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'wallet': Wallet,
  'wifi': Wifi,
  'wrench': Wrench,
  'zap': Zap,
};

/** Lo que se ofrece al crear o editar una categoría. */
export const ICONOS_DE_CATEGORIA: readonly { nombre: string; etiqueta: string }[] = [
  { nombre: 'house', etiqueta: 'Vivienda' },
  { nombre: 'zap', etiqueta: 'Energía' },
  { nombre: 'droplet', etiqueta: 'Agua' },
  { nombre: 'flame', etiqueta: 'Gas' },
  { nombre: 'wifi', etiqueta: 'Internet' },
  { nombre: 'smartphone', etiqueta: 'Telefonía' },
  { nombre: 'tv', etiqueta: 'Televisión' },
  { nombre: 'spray-can', etiqueta: 'Aseo' },
  { nombre: 'shopping-cart', etiqueta: 'Mercado' },
  { nombre: 'utensils-crossed', etiqueta: 'Restaurantes' },
  { nombre: 'coffee', etiqueta: 'Café' },
  { nombre: 'beer', etiqueta: 'Salidas' },
  { nombre: 'car', etiqueta: 'Vehículo' },
  { nombre: 'fuel', etiqueta: 'Combustible' },
  { nombre: 'bus', etiqueta: 'Transporte' },
  { nombre: 'bike', etiqueta: 'Bicicleta' },
  { nombre: 'plane', etiqueta: 'Viajes' },
  { nombre: 'circle-parking', etiqueta: 'Parqueadero' },
  { nombre: 'heart-pulse', etiqueta: 'Salud' },
  { nombre: 'stethoscope', etiqueta: 'Consultas' },
  { nombre: 'pill', etiqueta: 'Medicamentos' },
  { nombre: 'dumbbell', etiqueta: 'Gimnasio' },
  { nombre: 'graduation-cap', etiqueta: 'Educación' },
  { nombre: 'book-open', etiqueta: 'Libros' },
  { nombre: 'backpack', etiqueta: 'Colegio' },
  { nombre: 'baby', etiqueta: 'Bebé' },
  { nombre: 'dog', etiqueta: 'Mascotas' },
  { nombre: 'shirt', etiqueta: 'Ropa' },
  { nombre: 'scissors', etiqueta: 'Peluquería' },
  { nombre: 'gift', etiqueta: 'Regalos' },
  { nombre: 'party-popper', etiqueta: 'Celebraciones' },
  { nombre: 'film', etiqueta: 'Cine' },
  { nombre: 'music', etiqueta: 'Música' },
  { nombre: 'gamepad-2', etiqueta: 'Videojuegos' },
  { nombre: 'ticket', etiqueta: 'Entradas' },
  { nombre: 'laptop', etiqueta: 'Tecnología' },
  { nombre: 'briefcase', etiqueta: 'Trabajo' },
  { nombre: 'landmark', etiqueta: 'Impuestos' },
  { nombre: 'credit-card', etiqueta: 'Tarjetas' },
  { nombre: 'banknote', etiqueta: 'Efectivo' },
  { nombre: 'piggy-bank', etiqueta: 'Ahorro' },
  { nombre: 'receipt', etiqueta: 'Facturas' },
  { nombre: 'shield-check', etiqueta: 'Seguros' },
  { nombre: 'wrench', etiqueta: 'Mantenimiento' },
  { nombre: 'sofa', etiqueta: 'Hogar' },
  { nombre: 'hand-heart', etiqueta: 'Donaciones' },
  { nombre: 'store', etiqueta: 'Compras' },
  { nombre: 'package', etiqueta: 'Envíos' },
  { nombre: 'users', etiqueta: 'Familia' },
  { nombre: 'wallet', etiqueta: 'General' },
];

/**
 * Pinta el icono de una categoría.
 *
 * Con un nombre que no está en la tabla —uno sembrado hace tiempo, uno escrito
 * a mano en la base— no se pinta NADA en vez de pintar un interrogante: un
 * icono equivocado dice algo falso dla categoría, y ninguno no dice nada, que es
 * exactamente lo que se sabe.
 */
export function IconoDeCategoria({
  nombre,
  className,
}: {
  nombre?: string | null;
  className?: string;
}) {
  const Icono = nombre ? POR_NOMBRE[nombre] : undefined;
  if (!Icono) return null;

  return <Icono className={cn('size-4', className)} aria-hidden="true" />;
}
