#!/usr/bin/env node
//
// Runs arbitrary SQL against Coco's database. Read and write.
//
// ── Why it exists ────────────────────────────────────────────────────────────
// To inspect and fix DATA without opening Prisma Studio or a graphical
// client: see why a balance does not add up, count the rows of an import
// batch, fix a misassigned category.
//
// It is NOT the way to change the STRUCTURE. A `CREATE TABLE` written here
// would be left out of prisma/migrations and schema.prisma, and the next
// migration generated by `migrate diff` would try to create the table again —
// or worse, drop the one created by hand. The structure changes in
// schema.prisma and is materialised with scripts/new-migration.sh.
//
// ── Why it does not read the credentials ─────────────────────────────────────
// `dotenv -e` injects DATABASE_URL into the process environment. This file
// never opens it, never prints it and never passes it on the command line,
// where it would be visible in `ps` to any process on the machine.
import { createPrisma } from './db/prisma-client.mjs';
import { readFileSync } from 'node:fs';

const args = process.argv.slice(2);
const force = args.includes('--force');
const json = args.includes('--json');
const fromFile = args.includes('--file');
const rest = args.filter((a) => !a.startsWith('--'));

if (rest.length === 0) {
  console.error(`Usage:
  npm run sql -- "SELECT ..."          runs one statement
  npm run sql -- --file query.sql
  npm run sql -- --json "SELECT ..."   JSON output instead of a table
  npm run sql -- --force "DELETE ..."  allows destructive statements`);
  process.exit(1);
}

const sql = (fromFile ? readFileSync(rest[0], 'utf8') : rest.join(' ')).trim();

// The guard does not protect from a syntax error, it protects from
// carelessness: a DELETE without WHERE empties a whole table, and outside a
// transaction there is no undoing it. Asking for --force makes you type it on
// purpose.
const destructive =
  /^\s*(DROP\s+(DATABASE|SCHEMA|TABLE)|TRUNCATE)\b/i.test(sql) ||
  (/^\s*(DELETE|UPDATE)\b/i.test(sql) && !/\bWHERE\b/i.test(sql));

if (destructive && !force) {
  console.error(
    `Destructive statement without --force:\n  ${sql.split('\n')[0]}\n\n` +
      `If it is on purpose, run it again with --force.`,
  );
  process.exit(1);
}

// SELECT/SHOW/DESCRIBE return rows; the rest return how many they touched.
const returnsRows = /^\s*(SELECT|SHOW|DESCRIBE|DESC|EXPLAIN|WITH)\b/i.test(sql);

const prisma = createPrisma();

// BigInt does not survive JSON.stringify and Decimal would print as an object.
// Both show up all the time here: COUNT() is BigInt and every amount in Coco
// is Decimal.
const readable = (v) =>
  typeof v === 'bigint' ? Number(v) : v?.constructor?.name === 'Decimal' ? v.toString() : v;

try {
  if (returnsRows) {
    const rows = await prisma.$queryRawUnsafe(sql);
    const plain = rows.map((row) =>
      Object.fromEntries(Object.entries(row).map(([k, v]) => [k, readable(v)])),
    );
    if (json) console.log(JSON.stringify(plain, null, 2));
    else if (plain.length === 0) console.log('(no rows)');
    else console.table(plain);
    console.log(`${plain.length} row(s)`);
  } else {
    const affected = await prisma.$executeRawUnsafe(sql);
    console.log(`${affected} row(s) affected`);
  }
} catch (e) {
  console.error(`Database error: ${e.message.split('\n').slice(-3).join('\n')}`);
  process.exitCode = 1;
} finally {
  await prisma.$disconnect();
}
